CREATE TABLE team_standings (
    rk INT,
    squad TEXT PRIMARY KEY,
    mp INT,
    w INT,
    d INT,
    l INT,
    gf INT,
    ga INT,
    gd INT,
    pts INT,
    pts_mp NUMERIC,
    xg NUMERIC,
    xga NUMERIC,
    xgd NUMERIC,
    xgd_90 NUMERIC,
    last_5 TEXT,
    attendance INT,
    top_team_scorer TEXT,
    goalkeeper TEXT
);

CREATE TABLE team_standard (
    squad TEXT PRIMARY KEY,
    playing_time_mp INT,
	playing_time_starts INT,
	playing_time_min INT,
	playing_time_90s NUMERIC,
	performance_gls INT,
	performance_ast INT,
	performance_ga INT,
	performance_gpk INT,
	performance_pk INT,
	performance_pkatt INT,
	performance_crdy INT,
	performance_crdr INT,
	expected_xg NUMERIC,
	expected_npxg NUMERIC,
	expected_xag NUMERIC,
	expected_npxgxag NUMERIC,
	progression_prgc INT,
	progression_prgp INT,
	per_90_minutes_gls NUMERIC,
	per_90_minutes_ast NUMERIC,
	per_90_minutes_ga NUMERIC,
	per_90_minutes_gpk NUMERIC,
	per_90_minutes_gapk NUMERIC,
	per_90_minutes_xg NUMERIC,
	per_90_minutes_xag NUMERIC,
	per_90_minutes_xgxag NUMERIC,
	per_90_minutes_npxg NUMERIC,
	per_90_minutes_npxgxag NUMERIC
);

CREATE TABLE team_shooting (
    squad TEXT PRIMARY KEY,
    standard_gls INT,
	standard_sh INT,
	standard_sot INT,
	standard_sot_1 NUMERIC,
	standard_sh_90 NUMERIC,
	standard_sot_90 NUMERIC,
	standard_g_sh NUMERIC,
	standard_g_sot NUMERIC,
	standard_dist NUMERIC,
	standard_fk INT,
	standard_pk INT,
	standard_pkatt INT,
	expected_xg NUMERIC,
	expected_npxg NUMERIC,
	expected_npxg_sh NUMERIC,
	expected_gxg NUMERIC,
	expected_npgxg NUMERIC
);

CREATE TABLE team_passing (
    squad TEXT PRIMARY KEY,
    total_cmp INT,
	total_att INT,
	total_cmp_pct NUMERIC,
	total_totdist INT,
	total_prgdist INT,
	short_cmp INT,
	short_att INT,
	short_cmp_pct NUMERIC,
	medium_cmp INT,
	medium_att INT,
	medium_cmp_pct NUMERIC,
	long_cmp INT,
	long_att NUMERIC,
	long_cmp_pct NUMERIC,
	expected_xa NUMERIC,
	expected_axag NUMERIC
);

CREATE TABLE team_pass_types (
    squad TEXT PRIMARY KEY,
    pass_types_live INT,
	pass_types_dead INT,
	pass_types_fk INT,
	pass_types_tb INT,
	pass_types_sw INT,
	pass_types_crs INT,
	pass_types_ti INT,
	pass_types_ck INT,
	corner_kicks_in INT,
	corner_kicks_out INT,
	corner_kicks_str INT,
	outcomes_cmp INT,
	outcomes_off INT,
	outcomes_blocks INT
);

CREATE TABLE team_shot_creation (
    squad TEXT PRIMARY KEY,
    sca_sca INT,
    sca_per90 NUMERIC,
    sca_types_passlive INT,
    sca_types_passdead INT,
    sca_types_to INT,
    sca_types_sh INT,
    sca_types_fld INT,
    sca_types_def INT,
    gca_gca INT,
    gca_gca90 NUMERIC,
    gca_types_passlive INT,
    gca_types_passdead INT,
    gca_types_to INT,
    gca_types_sh INT,
    gca_types_fld INT,
    gca_types_def INT
);

CREATE TABLE team_defensive (
    squad TEXT PRIMARY KEY,
    tackles_tkl INT,
    tackles_tklw INT,
    tackles_def_3rd INT,
    tackles_mid_3rd INT,
    tackles_att_3rd INT,
    challenges_tkl INT,
    challenges_att INT,
	challenges_tkl_pct NUMERIC,
    challenges_lost INT,
    blocks_blocks INT,
	blocks_sh INT,
	blocks_pass INT
);

CREATE TABLE team_possession (
    squad TEXT PRIMARY KEY,
	poss NUMERIC,
    touches_touches INT,
    touches_def_pen INT,
    touches_def_3rd INT,
    touches_mid_3rd INT,
    touches_att_3rd INT,
    touches_att_pen INT,
    touches_live INT,
    takeons_att INT,
    takeons_succ INT,
    takeons_succ_pct NUMERIC,
	takeons_tkld INT,
	takeons_tkld_pct NUMERIC,
    carries_carries INT,
    carries_totdist INT,
    carries_prgdist INT,
    carries_prgc INT,
    carries_1_3 INT,
    carries_cpa INT,
    carries_mis INT,
    carries_dis INT,
    receiving_rec INT,
    receiving_prgr INT
);

CREATE TABLE team_playing_time (
    squad TEXT PRIMARY KEY,
    playing_time_mp INT,
	playing_time_min INT,
	playing_time_mn_mp INT,
	playing_time_min_1 INT,
	playing_time_90s NUMERIC,
	starts_starts INT,
	starts_mn_start INT,
	starts_compl INT,
	subs_subs INT,
	subs_mn_sub INT,
	subs_unsub INT,
	team_success_ppm NUMERIC,
	team_success_ong INT,
	team_success_onga INT,
	team_success INT,
	team_success_90 NUMERIC,
	team_success_xg_onxg NUMERIC,
	team_success_xg_onxga NUMERIC,
	team_success_xg_xg NUMERIC,
	team_success_xg_xg_90 NUMERIC
);
